spring.application.name=quiz-battle

spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB:quizbattle}
spring.datasource.username=${POSTGRES_USER:quizbattle}
spring.datasource.password=${POSTGRES_PASSWORD:quizbattle}

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# just for a warning to disappear
spring.jpa.open-in-view=false